AIC_Stage1/AIC_Stage1.v11.suo
AIC_Stage1/SentimentClient/App.config
AIC_Stage1/SentimentClient/Program.cs
AIC_Stage1/SentimentClient/SentimentClient.csproj
AIC_Stage1/SentimentClient/Service References/Authenticator/Authenticator.wsdl
AIC_Stage1/SentimentClient/Service References/Authenticator/Reference.cs
AIC_Stage1/SentimentClient/Service References/Authenticator/Reference.svcmap
AIC_Stage1/SentimentClient/Service References/Authenticator/configuration.svcinfo
AIC_Stage1/SentimentClient/Service References/Authenticator/configuration91.svcinfo
AIC_Stage1/SentimentClient/Service References/Authenticator/item.disco
AIC_Stage1/SentimentClient/Service References/Authenticator/item.xsd
AIC_Stage1/SentimentClient/Service References/Authenticator/item1.xsd
AIC_Stage1/SentimentClient/Service References/StatisticServiceReference/Reference.cs
AIC_Stage1/SentimentClient/Service References/StatisticServiceReference/Reference.svcmap
AIC_Stage1/SentimentClient/Service References/StatisticServiceReference/StatisticService.wsdl
AIC_Stage1/SentimentClient/Service References/StatisticServiceReference/configuration.svcinfo
AIC_Stage1/SentimentClient/Service References/StatisticServiceReference/configuration91.svcinfo
AIC_Stage1/SentimentClient/Service References/StatisticServiceReference/item.disco
AIC_Stage1/SentimentClient/Service References/StatisticServiceReference/item.xsd
AIC_Stage1/SentimentClient/Service References/StatisticServiceReference/item1.xsd
AIC_Stage1/SentimentClient/bin/Debug/SentimentClient.vshost.exe.config
AIC_Stage1/SentimentClient/obj/Debug/DesignTimeResolveAssemblyReferences.cache
AIC_Stage1/SentimentClient/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
AIC_Stage1/SentimentClient/obj/Debug/SentimentClient.csproj.FileListAbsolute.txt
AIC_Stage1/SentimentClient/obj/Debug/TempPE/Service References.Authenticator.Reference.cs.dll
AIC_Stage1/SentimentClient/obj/Debug/TempPE/Service References.StatisticServiceReference.Reference.cs.dll
AIC_Stage1/SentimentHost/Program.cs
AIC_Stage1/SentimentHost/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
AIC_Stage1/SentimentHost/obj/Debug/SentimentHost.csproj.FileListAbsolute.txt
AIC_Stage1/SentimentLib/App.config
AIC_Stage1/SentimentLib/Authenticator.cs
AIC_Stage1/SentimentLib/IAuthenticator.cs
AIC_Stage1/SentimentLib/IUserDao.cs
AIC_Stage1/SentimentLib/MySqlDriver.cs
AIC_Stage1/SentimentLib/SentimentLib.csproj
AIC_Stage1/SentimentLib/SentimentLib.csproj.user
AIC_Stage1/SentimentLib/StatisticService.cs
AIC_Stage1/SentimentLib/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
AIC_Stage1/SentimentLib/obj/Debug/SentimentLib.csproj.FileListAbsolute.txt
