
package org.eclipse.bpel.validatelogin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "validateLoginPortType", targetNamespace = "http://eclipse.org/bpel/validateLogin")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.eclipse.bpel.validatelogin.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface ValidateLoginPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns org.eclipse.bpel.validatelogin.ValidateLoginResponse
     */
    @WebMethod(action = "http://eclipse.org/bpel/validateLogin/process")
    @WebResult(name = "validateLoginResponse", targetNamespace = "http://eclipse.org/bpel/validateLogin", partName = "payload")
    public ValidateLoginResponse process(
        @WebParam(name = "validateLoginRequest", targetNamespace = "http://eclipse.org/bpel/validateLogin", partName = "payload")
        ValidateLoginRequest payload);

}
