//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillDetails", Namespace="http://schemas.datacontract.org/2004/07/BillingService")]
    public partial class BillDetails : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double amountField;
        
        private int customerIdField;
        
        private string customerUsernameField;
        
        private int idField;
        
        private bool isPayedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerUsername
        {
            get
            {
                return this.customerUsernameField;
            }
            set
            {
                this.customerUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isPayed
        {
            get
            {
                return this.isPayedField;
            }
            set
            {
                this.isPayedField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBillingService")]
public interface IBillingService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ListUsersBills", ReplyAction="http://tempuri.org/IBillingService/ListUsersBillsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentException), Action="http://tempuri.org/IBillingService/ListUsersBillsArgumentExceptionFault", Name="ArgumentException", Namespace="http://schemas.datacontract.org/2004/07/System")]
    int[] ListUsersBills(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/ListUsersBills", ReplyAction="http://tempuri.org/IBillingService/ListUsersBillsResponse")]
    System.Threading.Tasks.Task<int[]> ListUsersBillsAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetBill", ReplyAction="http://tempuri.org/IBillingService/GetBillResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentException), Action="http://tempuri.org/IBillingService/GetBillArgumentExceptionFault", Name="ArgumentException", Namespace="http://schemas.datacontract.org/2004/07/System")]
    BillingService.BillDetails GetBill(int Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/GetBill", ReplyAction="http://tempuri.org/IBillingService/GetBillResponse")]
    System.Threading.Tasks.Task<BillingService.BillDetails> GetBillAsync(int Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/PayBill", ReplyAction="http://tempuri.org/IBillingService/PayBillResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentException), Action="http://tempuri.org/IBillingService/PayBillArgumentExceptionFault", Name="ArgumentException", Namespace="http://schemas.datacontract.org/2004/07/System")]
    void PayBill(int Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/PayBill", ReplyAction="http://tempuri.org/IBillingService/PayBillResponse")]
    System.Threading.Tasks.Task PayBillAsync(int Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CalculateBillsForUser", ReplyAction="http://tempuri.org/IBillingService/CalculateBillsForUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(System.ArgumentException), Action="http://tempuri.org/IBillingService/CalculateBillsForUserArgumentExceptionFault", Name="ArgumentException", Namespace="http://schemas.datacontract.org/2004/07/System")]
    void CalculateBillsForUser(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CalculateBillsForUser", ReplyAction="http://tempuri.org/IBillingService/CalculateBillsForUserResponse")]
    System.Threading.Tasks.Task CalculateBillsForUserAsync(string username);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBillingServiceChannel : IBillingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BillingServiceClient : System.ServiceModel.ClientBase<IBillingService>, IBillingService
{
    
    public BillingServiceClient()
    {
    }
    
    public BillingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BillingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BillingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BillingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int[] ListUsersBills(string username)
    {
        return base.Channel.ListUsersBills(username);
    }
    
    public System.Threading.Tasks.Task<int[]> ListUsersBillsAsync(string username)
    {
        return base.Channel.ListUsersBillsAsync(username);
    }
    
    public BillingService.BillDetails GetBill(int Id)
    {
        return base.Channel.GetBill(Id);
    }
    
    public System.Threading.Tasks.Task<BillingService.BillDetails> GetBillAsync(int Id)
    {
        return base.Channel.GetBillAsync(Id);
    }
    
    public void PayBill(int Id)
    {
        base.Channel.PayBill(Id);
    }
    
    public System.Threading.Tasks.Task PayBillAsync(int Id)
    {
        return base.Channel.PayBillAsync(Id);
    }
    
    public void CalculateBillsForUser(string username)
    {
        base.Channel.CalculateBillsForUser(username);
    }
    
    public System.Threading.Tasks.Task CalculateBillsForUserAsync(string username)
    {
        return base.Channel.CalculateBillsForUserAsync(username);
    }
}
