//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStatistic")]
public interface IStatistic
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatistic/getStatisticValue", ReplyAction="http://tempuri.org/IStatistic/getStatisticValueResponse")]
    double getStatisticValue(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatistic/getStatisticValue", ReplyAction="http://tempuri.org/IStatistic/getStatisticValueResponse")]
    System.Threading.Tasks.Task<double> getStatisticValueAsync(string username);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStatisticChannel : IStatistic, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StatisticClient : System.ServiceModel.ClientBase<IStatistic>, IStatistic
{
    
    public StatisticClient()
    {
    }
    
    public StatisticClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StatisticClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StatisticClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StatisticClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double getStatisticValue(string username)
    {
        return base.Channel.getStatisticValue(username);
    }
    
    public System.Threading.Tasks.Task<double> getStatisticValueAsync(string username)
    {
        return base.Channel.getStatisticValueAsync(username);
    }
}
