
package org.eclipse.bpel.sample3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "registerUserPortType", targetNamespace = "http://eclipse.org/bpel/sample3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.eclipse.bpel.sample3.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface RegisterUserPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns org.eclipse.bpel.sample3.RegisterUserResponse
     */
    @WebMethod(action = "http://eclipse.org/bpel/sample3/process")
    @WebResult(name = "registerUserResponse", targetNamespace = "http://eclipse.org/bpel/sample3", partName = "payload")
    public RegisterUserResponse process(
        @WebParam(name = "registerUserRequest", targetNamespace = "http://eclipse.org/bpel/sample3", partName = "payload")
        RegisterUserRequest payload);

}
