
package org.eclipse.bpel.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "billingPortType", targetNamespace = "http://eclipse.org/bpel/sample")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.billingservice.ObjectFactory.class,
    org.tempuri.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class,
    org.eclipse.bpel.sample.ObjectFactory.class
})
public interface BillingPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns org.eclipse.bpel.sample.BillingResponse
     */
    @WebMethod(action = "http://eclipse.org/bpel/sample/initiate")
    @WebResult(name = "billingResponse", targetNamespace = "http://eclipse.org/bpel/sample", partName = "payload")
    public BillingResponse initiate(
        @WebParam(name = "billingRequest", targetNamespace = "http://eclipse.org/bpel/sample", partName = "payload")
        BillingRequest payload);

}
