
package org.eclipse.bpel.sample;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "billing", targetNamespace = "http://eclipse.org/bpel/sample", wsdlLocation = "http://localhost:8080/ode/processes/billing?wsdl")
public class Billing
    extends Service
{

    private final static URL BILLING_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.eclipse.bpel.sample.Billing.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.eclipse.bpel.sample.Billing.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ode/processes/billing?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ode/processes/billing?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BILLING_WSDL_LOCATION = url;
    }

    public Billing(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Billing() {
        super(BILLING_WSDL_LOCATION, new QName("http://eclipse.org/bpel/sample", "billing"));
    }

    /**
     * 
     * @return
     *     returns BillingPortType
     */
    @WebEndpoint(name = "billingSOAP11port_http")
    public BillingPortType getBillingSOAP11PortHttp() {
        return super.getPort(new QName("http://eclipse.org/bpel/sample", "billingSOAP11port_http"), BillingPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillingPortType
     */
    @WebEndpoint(name = "billingSOAP11port_http")
    public BillingPortType getBillingSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://eclipse.org/bpel/sample", "billingSOAP11port_http"), BillingPortType.class, features);
    }

}
