
package org.eclipse.bpel.sample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getBillDetailsService", targetNamespace = "http://eclipse.org/bpel/sample", wsdlLocation = "file:/home/bernhard/Projects/Uni/bill2/bpelContent/getBillDetailsArtifacts.wsdl")
public class GetBillDetailsService
    extends Service
{

    private final static URL GETBILLDETAILSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETBILLDETAILSSERVICE_EXCEPTION;
    private final static QName GETBILLDETAILSSERVICE_QNAME = new QName("http://eclipse.org/bpel/sample", "getBillDetailsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/bernhard/Projects/Uni/bill2/bpelContent/getBillDetailsArtifacts.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETBILLDETAILSSERVICE_WSDL_LOCATION = url;
        GETBILLDETAILSSERVICE_EXCEPTION = e;
    }

    public GetBillDetailsService() {
        super(__getWsdlLocation(), GETBILLDETAILSSERVICE_QNAME);
    }

    public GetBillDetailsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETBILLDETAILSSERVICE_QNAME, features);
    }

    public GetBillDetailsService(URL wsdlLocation) {
        super(wsdlLocation, GETBILLDETAILSSERVICE_QNAME);
    }

    public GetBillDetailsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETBILLDETAILSSERVICE_QNAME, features);
    }

    public GetBillDetailsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetBillDetailsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetBillDetails
     */
    @WebEndpoint(name = "getBillDetailsPort")
    public GetBillDetails getGetBillDetailsPort() {
        return super.getPort(new QName("http://eclipse.org/bpel/sample", "getBillDetailsPort"), GetBillDetails.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetBillDetails
     */
    @WebEndpoint(name = "getBillDetailsPort")
    public GetBillDetails getGetBillDetailsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eclipse.org/bpel/sample", "getBillDetailsPort"), GetBillDetails.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETBILLDETAILSSERVICE_EXCEPTION!= null) {
            throw GETBILLDETAILSSERVICE_EXCEPTION;
        }
        return GETBILLDETAILSSERVICE_WSDL_LOCATION;
    }

}
