
package org.eclipse.bpel.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "getBillDetailsPortType", targetNamespace = "http://eclipse.org/bpel/sample")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetBillDetailsPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns org.eclipse.bpel.sample.GetBillDetailsResponse
     */
    @WebMethod(action = "http://eclipse.org/bpel/sample/process")
    @WebResult(name = "getBillDetailsResponse", targetNamespace = "http://eclipse.org/bpel/sample", partName = "payload")
    public GetBillDetailsResponse process(
        @WebParam(name = "getBillDetailsRequest", targetNamespace = "http://eclipse.org/bpel/sample", partName = "payload")
        GetBillDetailsRequest payload);

}
