
package org.eclipse.bpel.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "getBillListPortType", targetNamespace = "http://eclipse.org/bpel/sample")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetBillListPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns org.eclipse.bpel.sample.GetBillListResponse
     */
    @WebMethod(action = "http://eclipse.org/bpel/sample/process")
    @WebResult(name = "getBillListResponse", targetNamespace = "http://eclipse.org/bpel/sample", partName = "payload")
    public GetBillListResponse process(
        @WebParam(name = "getBillListRequest", targetNamespace = "http://eclipse.org/bpel/sample", partName = "payload")
        GetBillListRequest payload);

}
