
package org.eclipse.bpel.sample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getBillListService", targetNamespace = "http://eclipse.org/bpel/sample", wsdlLocation = "file:/home/bernhard/Projects/Uni/bill2/bpelContent/getBillListArtifacts.wsdl")
public class GetBillListService
    extends Service
{

    private final static URL GETBILLLISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETBILLLISTSERVICE_EXCEPTION;
    private final static QName GETBILLLISTSERVICE_QNAME = new QName("http://eclipse.org/bpel/sample", "getBillListService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/bernhard/Projects/Uni/bill2/bpelContent/getBillListArtifacts.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETBILLLISTSERVICE_WSDL_LOCATION = url;
        GETBILLLISTSERVICE_EXCEPTION = e;
    }

    public GetBillListService() {
        super(__getWsdlLocation(), GETBILLLISTSERVICE_QNAME);
    }

    public GetBillListService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETBILLLISTSERVICE_QNAME, features);
    }

    public GetBillListService(URL wsdlLocation) {
        super(wsdlLocation, GETBILLLISTSERVICE_QNAME);
    }

    public GetBillListService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETBILLLISTSERVICE_QNAME, features);
    }

    public GetBillListService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetBillListService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetBillList
     */
    @WebEndpoint(name = "getBillListPort")
    public GetBillList getGetBillListPort() {
        return super.getPort(new QName("http://eclipse.org/bpel/sample", "getBillListPort"), GetBillList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetBillList
     */
    @WebEndpoint(name = "getBillListPort")
    public GetBillList getGetBillListPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://eclipse.org/bpel/sample", "getBillListPort"), GetBillList.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETBILLLISTSERVICE_EXCEPTION!= null) {
            throw GETBILLLISTSERVICE_EXCEPTION;
        }
        return GETBILLLISTSERVICE_WSDL_LOCATION;
    }

}
