
package com.fluidtime.exampleMVC.statistic_client.com.mytest.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CallerPortType", targetNamespace = "http://MyTest.com/Test")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	com.fluidtime.exampleMVC.statistic_client.org.tempuri.ObjectFactory.class,
	com.fluidtime.exampleMVC.statistic_client.com.mytest.test.ObjectFactory.class,
	com.fluidtime.exampleMVC.statistic_client.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class
})
public interface CallerPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns com.mytest.test.CallerResponse
     */
    @WebMethod(action = "http://MyTest.com/Test/process")
    @WebResult(name = "CallerResponse", targetNamespace = "http://MyTest.com/Test", partName = "payload")
    public CallerResponse process(
        @WebParam(name = "CallerRequest", targetNamespace = "http://MyTest.com/Test", partName = "payload")
        CallerRequest payload);

}
