
package com.fluidtime.exampleMVC.statistic_client.com.mytest.test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Caller", targetNamespace = "http://MyTest.com/Test", wsdlLocation = "http://localhost:8080/ode/processes/Caller?wsdl")
public class Caller
    extends Service
{

    private final static URL CALLER_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.fluidtime.exampleMVC.statistic_client.com.mytest.test.Caller.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ode/processes/Caller?wsdl");
        } catch (MalformedURLException e) {
        }
        CALLER_WSDL_LOCATION = url;
    }

    public Caller(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Caller() {
        super(CALLER_WSDL_LOCATION, new QName("http://MyTest.com/Test", "Caller"));
    }

    /**
     * 
     * @return
     *     returns CallerPortType
     */
    @WebEndpoint(name = "CallerSOAP11port_http")
    public CallerPortType getCallerSOAP11PortHttp() {
        return super.getPort(new QName("http://MyTest.com/Test", "CallerSOAP11port_http"), CallerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CallerPortType
     */
    @WebEndpoint(name = "CallerSOAP11port_http")
    public CallerPortType getCallerSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://MyTest.com/Test", "CallerSOAP11port_http"), CallerPortType.class, features);
    }

}
