//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentimentClient.StatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StatServiceReference.IStatistic")]
    public interface IStatistic {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatistic/getStatisticValue", ReplyAction="http://tempuri.org/IStatistic/getStatisticValueResponse")]
        double getStatisticValue(string company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStatistic/getStatisticValue", ReplyAction="http://tempuri.org/IStatistic/getStatisticValueResponse")]
        System.Threading.Tasks.Task<double> getStatisticValueAsync(string company);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStatisticChannel : SentimentClient.StatServiceReference.IStatistic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticClient : System.ServiceModel.ClientBase<SentimentClient.StatServiceReference.IStatistic>, SentimentClient.StatServiceReference.IStatistic {
        
        public StatisticClient() {
        }
        
        public StatisticClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getStatisticValue(string company) {
            return base.Channel.getStatisticValue(company);
        }
        
        public System.Threading.Tasks.Task<double> getStatisticValueAsync(string company) {
            return base.Channel.getStatisticValueAsync(company);
        }
    }
}
