//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentimentClient.AuthenticatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticatorServiceReference.IAuthenticator")]
    public interface IAuthenticator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/validateLogin", ReplyAction="http://tempuri.org/IAuthenticator/validateLoginResponse")]
        bool validateLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/validateLogin", ReplyAction="http://tempuri.org/IAuthenticator/validateLoginResponse")]
        System.Threading.Tasks.Task<bool> validateLoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/getCompanyFromUsername", ReplyAction="http://tempuri.org/IAuthenticator/getCompanyFromUsernameResponse")]
        string getCompanyFromUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/getCompanyFromUsername", ReplyAction="http://tempuri.org/IAuthenticator/getCompanyFromUsernameResponse")]
        System.Threading.Tasks.Task<string> getCompanyFromUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/isLoggedIn", ReplyAction="http://tempuri.org/IAuthenticator/isLoggedInResponse")]
        bool isLoggedIn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/isLoggedIn", ReplyAction="http://tempuri.org/IAuthenticator/isLoggedInResponse")]
        System.Threading.Tasks.Task<bool> isLoggedInAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/register", ReplyAction="http://tempuri.org/IAuthenticator/registerResponse")]
        bool register(string username, string password, string firstname, string lastname, string email, string creditcard, string company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/register", ReplyAction="http://tempuri.org/IAuthenticator/registerResponse")]
        System.Threading.Tasks.Task<bool> registerAsync(string username, string password, string firstname, string lastname, string email, string creditcard, string company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/unregister", ReplyAction="http://tempuri.org/IAuthenticator/unregisterResponse")]
        bool unregister(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticator/unregister", ReplyAction="http://tempuri.org/IAuthenticator/unregisterResponse")]
        System.Threading.Tasks.Task<bool> unregisterAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticatorChannel : SentimentClient.AuthenticatorServiceReference.IAuthenticator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticatorClient : System.ServiceModel.ClientBase<SentimentClient.AuthenticatorServiceReference.IAuthenticator>, SentimentClient.AuthenticatorServiceReference.IAuthenticator {
        
        public AuthenticatorClient() {
        }
        
        public AuthenticatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool validateLogin(string username, string password) {
            return base.Channel.validateLogin(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> validateLoginAsync(string username, string password) {
            return base.Channel.validateLoginAsync(username, password);
        }
        
        public string getCompanyFromUsername(string username) {
            return base.Channel.getCompanyFromUsername(username);
        }
        
        public System.Threading.Tasks.Task<string> getCompanyFromUsernameAsync(string username) {
            return base.Channel.getCompanyFromUsernameAsync(username);
        }
        
        public bool isLoggedIn() {
            return base.Channel.isLoggedIn();
        }
        
        public System.Threading.Tasks.Task<bool> isLoggedInAsync() {
            return base.Channel.isLoggedInAsync();
        }
        
        public bool register(string username, string password, string firstname, string lastname, string email, string creditcard, string company) {
            return base.Channel.register(username, password, firstname, lastname, email, creditcard, company);
        }
        
        public System.Threading.Tasks.Task<bool> registerAsync(string username, string password, string firstname, string lastname, string email, string creditcard, string company) {
            return base.Channel.registerAsync(username, password, firstname, lastname, email, creditcard, company);
        }
        
        public bool unregister(string username) {
            return base.Channel.unregister(username);
        }
        
        public System.Threading.Tasks.Task<bool> unregisterAsync(string username) {
            return base.Channel.unregisterAsync(username);
        }
    }
}
